<a href="https://colab.research.google.com/github/hazelchiang2102/ADALL_github/blob/main/ADALL_Project_Draft_2401.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Core libraries
import pandas as pd
import numpy as np
# Visualisation
import matplotlib.pyplot as plt
# Modelling and preprocessing
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

In [4]:
# Example: Replace this with the raw URL of your GitHub file
github_raw_url = 'https://raw.githubusercontent.com/hazelchiang2102/ADALL_github/refs/heads/main/diabetes_binary_health_indicators_BRFSS2015.csv'
try:
    df = pd.read_csv(github_raw_url)
    print("Successfully loaded data from GitHub!")
    display(df.head())
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please ensure the URL is correct and the file format is compatible with `pd.read_csv`.")

Successfully loaded data from GitHub!


Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [5]:
df.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [7]:
from google.colab import userdata
from openai import OpenAI

# Load key from Google Colab Secrets
api_key = userdata.get('OPENAI_API_KEY')

client = OpenAI(
    api_key=api_key,
)

In [9]:
#generate a preview of ten rows as text first, so that we can use it for sending to LLM API later.
data_preview = df.head(10).to_string()
print(data_preview)

   Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0                   0.0           0.0     0.0      1.0                0.0            1.0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0     3.0
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0                   0.0           1.0     0.0      0.0                0.0            0.0          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0     1.0
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0                   0.0           0.0     1.0      0.0                0.0            1.0          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0     8.0
3              0.0     1.0       0.0        

In [11]:
#sending to LLM API
#generate a preview of ten rows as text first, so that we can use it for sending to LLM API later.
data_preview = df.head(10).to_string()
response = client.responses.create(
    model="gpt-5-mini",
    instructions="""
You are an expert data scientist with extensive knowledge of tree-based models.
Use ONLY the information inside the dataset profile text.
Do NOT invent correlations, columns, or values.
If something is not in the dataset profile, state 'Not shown in profile'.
Always justify recommendations using reasoning trace based ONLY on the dataset profile.
""",
    input=f"""Dataset info: {data_preview}\n
    Context:
    The business problem is to identify individuals at high risk of diabetes early and to predict the likelihood of diabetes using non-invasive, survey-based indicators (e.g. BMI, blood pressure, lifestyle habits), so that preventive interventions can be prioritised.\n
    Questions
    1. Based on the context and dataset info, how should i approach modelling objective? focus on problem framing aspects.
    2. What would be the most meaningful target?
    3. What would be most important metric for scoring?
    4. What are the top 3 most potentially important features?
    """)
print(response.output_text)

1) How to approach the modelling objective (problem framing)
- Framing: a supervised binary risk-prediction problem where the model should output a probability (risk score) that an individual has diabetes. Justification: the dataset contains a Diabetes_binary column (0/1) and the business goal is to "predict the likelihood of diabetes ... to prioritise preventive interventions."
- Desired output and operational use: produce calibrated probabilities so individuals can be ranked and thresholds set for intervention triage (high/medium/low risk). Justification: the business needs to prioritise interventions based on predicted likelihood.
- Losses / constraints to consider at framing time: prioritise reducing missed high-risk cases (false negatives) but also be explicit about the cost/capacity of interventions so you can choose an operating threshold. Note: specific costs, capacity limits and prevalence are Not shown in profile and must be provided to set an optimal operational threshold.
-

In [12]:
import pandas as pd
import numpy as np
from io import StringIO

# ---------------------------
# Generate a full dataset profile
# ---------------------------

buffer = StringIO()

# dtypes
buffer.write("=== DTYPES ===\n")
buffer.write(df.dtypes.to_string())
buffer.write("\n\n")

# numeric describe
buffer.write("=== NUMERIC DESCRIBE ===\n")
buffer.write(df.describe().to_string())
buffer.write("\n\n")

# categorical describe
buffer.write("=== CATEGORICAL DESCRIBE ===\n")
try:
    buffer.write(df.describe(include='object').to_string())
except:
    buffer.write("No categorical columns")
buffer.write("\n\n")

# null summary
buffer.write("=== NULL SUMMARY ===\n")
null_summary = (
    df.isna().sum().to_frame("null_count")
    .assign(null_pct=lambda x: x["null_count"]/len(df))
)
buffer.write(null_summary.to_string())
buffer.write("\n\n")

# unique cardinality
buffer.write("=== UNIQUE VALUES PER COLUMN ===\n")
buffer.write(df.nunique().to_frame("unique_count").to_string())
buffer.write("\n\n")

# correlation matrix
buffer.write("=== CORRELATIONS (NUMERIC ONLY) ===\n")
buffer.write(df.corr(numeric_only=True).round(3).to_string())
buffer.write("\n\n")

# value counts for categoricals
buffer.write("=== VALUE COUNTS (TOP 20 PER CATEGORICAL COLUMN) ===\n")
cat_cols = df.select_dtypes(include='object').columns
if len(cat_cols) > 0:
    for col in cat_cols:
        buffer.write(f"\nColumn: {col}\n")
        vc = df[col].value_counts().head(20)
        buffer.write(vc.to_string())
        buffer.write("\n")
else:
    buffer.write("No categorical columns\n")
buffer.write("\n")

# --------- FIXED OUTLIER COMPUTATION (NO BOOLEANS) ---------
buffer.write("=== OUTLIER SUMMARY (IQR METHOD) ===\n")
num_cols = df.select_dtypes(include=['number']).columns  # exclude booleans
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1
outliers = ((df[num_cols] < (Q1 - 1.5*IQR)) | (df[num_cols] > (Q3 + 1.5*IQR))).sum()
buffer.write(outliers.to_string())
buffer.write("\n\n")

# leakage scan: columns with all unique values
buffer.write("=== POSSIBLE LEAKAGE COLUMNS (UNIQUE FOR EACH ROW) ===\n")
leak_cols = df.columns[df.nunique() == len(df)]
buffer.write(str(list(leak_cols)))
buffer.write("\n\n")

# shape, duplicates, constant cols
buffer.write("=== SHAPE / DUPLICATES / CONSTANT COLUMNS ===\n")
dup_count = df.duplicated().sum()
constant_cols = df.columns[df.nunique() == 1].tolist()
buffer.write(f"Rows: {len(df)}, Columns: {df.shape[1]}\n")
buffer.write(f"Duplicate rows: {dup_count}\n")
buffer.write(f"Constant columns: {constant_cols}\n\n")

# Final text
payload_text = buffer.getvalue()

print(payload_text)

=== DTYPES ===
Diabetes_binary         float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
HeartDiseaseorAttack    float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64

=== NUMERIC DESCRIBE ===
       Diabetes_binary         HighBP       HighChol      CholCheck            BMI         Smoker         Stroke  HeartDiseaseorAttack   PhysActivity         Fruits        Veggies  HvyAlcoholConsump  AnyHealthcare    NoDocbcCost        GenHlth       MentH

In [13]:
response = client.responses.create(
    model="gpt-5-mini",
    instructions="""
You are an expert data scientist with extensive knowledge of tree-based models.
Always justify recommendations using reasoning trace based ONLY on the dataset profile.
""",
    input=f"""
Dataset info: {payload_text}\n
Questions:\n
1. Based on the dataset profile, what data quality issues should be resolved before modelling?
Provide a priority list and justify each item. \n
2. Which columns appear redundant, correlated, or likely to cause leakage?
Explain why each is problematic. \n
Next: Provide a python script to handle the identified issues.
Define one helper function for each issue.
Then define a wrapper function that calls these helper with true false option as user choice
Provide a single line of code to run the overall wrapper function.
Do not encode categorical columns or model first.
""")

print(response.output_text)


1) Data-quality issues to resolve before modeling — prioritized with justifications (based only on the dataset profile)

High priority
- Duplicate rows (remove or deduplicate)
  - Evidence: 24,206 duplicate rows out of 253,680 total (≈9.55% duplicates). Duplicate records can bias training and validation, inflate apparent sample size, and lead to overoptimistic performance estimates.
- Binary-valued columns stored as floats (cast to integer / category)
  - Evidence: Many columns have only 2 unique values (unique_count == 2: Diabetes_binary, HighBP, HighChol, CholCheck, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, DiffWalk, Sex). They are currently float64; converting to int8 or category improves memory, clarity, and downstream handling.
- Class imbalance in target (plan for during modeling or via resampling)
  - Evidence: Diabetes_binary mean ≈ 0.139 (13.9% positive). This is moderate-to-strong imbalance and should b

In [20]:
# ---------------------------
# One of the possible response from GPT.
# What are the differences with yours?
# How would you improve earlier prompt?
# ---------------------------

# Helper 1: remove duplicates
def remove_duplicates(df, inplace=False):
    """
    Remove exact duplicate rows.
    Returns (df_clean, n_removed).
    """
    if not inplace:
        df = df.copy()
    initial = len(df)
    df.drop_duplicates(inplace=True)
    removed = initial - len(df)
    return (df, removed)

# Helper 2: convert binary-like float columns to integer / category
def convert_binary_floats(df, inplace=False, as_category=False):
    """
    Detect columns with exactly 2 unique non-null values and integer-like (0/1)
    and convert them to integer (int8) or categorical.
    Returns (df_converted, cols_converted).
    """
    if not inplace:
        df = df.copy()
    cols_converted = []
    for col in df.columns:
        # consider only non-null unique values
        nunique = df[col].nunique(dropna=True)
        if nunique == 2:
            # check values are subset of {0,1} after rounding
            vals = set(pd.Series(df[col].dropna().unique()).astype(float).round(6))
            if vals.issubset({0.0, 1.0}):
                if as_category:
                    df[col] = df[col].astype('category')
                else:
                    df[col] = df[col].astype('int8')
                cols_converted.append(col)
    return (df, cols_converted)

# Helper 3: cap/winsorize outliers using IQR method (or percentile clipping option)
def cap_outliers_iqr(df, cols=None, factor=1.5, inplace=False):
    """
    For each specified column (or all numeric columns if cols is None),
    compute IQR and clip values to [Q1 - factor*IQR, Q3 + factor*IQR].
    Returns (df_capped, caps) where caps is dict of (col: (lower, upper)).
    """
    if not inplace:
        df = df.copy()
    numeric = df.select_dtypes(include=[np.number]).columns.tolist()
    if cols is None:
        cols = numeric
    caps = {}
    for col in cols:
        if col not in df.columns:
            continue
        series = df[col].dropna()
        if series.empty:
            continue
        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - factor * iqr
        upper = q3 + factor * iqr
        # only apply if bounds are finite
        if np.isfinite(lower) and np.isfinite(upper):
            df[col] = df[col].clip(lower=lower, upper=upper)
            caps[col] = (lower, upper)
    return (df, caps)

# Helper 4: drop highly correlated features (automated selection using target correlation)
def drop_correlated(df, target, threshold=0.45, inplace=False, exclude=None):
    """
    Drop one column from each pair with absolute correlation > threshold.
    Selection rule: for a correlated pair (a,b), drop the column with lower
    absolute Pearson correlation with the target. Never drop the target or
    columns in exclude list.
    Returns (df_reduced, dropped_cols)
    """
    if not inplace:
        df = df.copy()
    if exclude is None:
        exclude = []
    exclude = set(exclude) | {target}
    # compute correlations on numeric columns only
    numeric = df.select_dtypes(include=[np.number]).columns.tolist()
    corr = df[numeric].corr().abs()
    to_drop = set()
    dropped_cols = []
    # iterate upper triangle
    cols = corr.columns.tolist()
    for i in range(len(cols)):
        for j in range(i+1, len(cols)):
            a, b = cols[i], cols[j]
            if a in exclude or b in exclude:
                continue
            if corr.at[a, b] > threshold:
                # compare absolute corr with target (if present)
                corr_with_target = df[numeric].corr().abs().get(target)
                # If target not numeric or missing, fall back to mean absolute corr across others
                if target in numeric:
                    a_score = corr_with_target.get(a, 0.0)
                    b_score = corr_with_target.get(b, 0.0)
                else:
                    a_score = corr[a].mean()
                    b_score = corr[b].mean()
                # drop the one with smaller abs corr with target; tie-break by column name
                if a_score < b_score:
                    pick = a
                elif b_score < a_score:
                    pick = b
                else:
                    pick = min(a, b)
                if pick not in to_drop:
                    to_drop.add(pick)
                    dropped_cols.append(pick)
    df.drop(columns=list(to_drop), inplace=True)
    return (df, dropped_cols)

# Helper 5: simple target balancing (undersample or oversample). Use only when desired.
def balance_target_simple(df, target, method='undersample', random_state=42, inplace=False):
    """
    Simple balancing:
      - 'undersample': randomly downsample majority class to minority class size.
      - 'oversample': randomly upsample minority class with replacement to majority size.
    Returns (df_balanced, counts) where counts is dict of new class counts.
    """
    if not inplace:
        df = df.copy()
    if target not in df.columns:
        raise ValueError("target not in dataframe")
    counts = df[target].value_counts()
    if len(counts) < 2:
        return (df, counts.to_dict())
    classes = counts.index.tolist()
    c0, c1 = classes[0], classes[1]
    n0, n1 = counts.iloc[0], counts.iloc[1]
    rng = np.random.RandomState(random_state)
    if method == 'undersample':
        # downsample majority
        if n0 > n1:
            maj, minc = c0, c1
            n_min = n1
        else:
            maj, minc = c1, c0
            n_min = n0
        maj_df = df[df[target] == maj].sample(n=n_min, random_state=random_state)
        min_df = df[df[target] == minc]
        df_bal = pd.concat([maj_df, min_df]).sample(frac=1.0, random_state=random_state).reset_index(drop=True)
    elif method == 'oversample':
        # upsample minority
        if n0 < n1:
            minc = c0
            n_maj = n1
        else:
            minc = c1
            n_maj = n0
        min_df = df[df[target] == minc]
        n_to_sample = n_maj
        sampled = min_df.sample(n=n_to_sample, replace=True, random_state=random_state)
        maj_df = df[df[target] != minc]
        df_bal = pd.concat([maj_df, sampled]).sample(frac=1.0, random_state=random_state).reset_index(drop=True)
    else:
        raise ValueError("method must be 'undersample' or 'oversample'")
    return (df_bal, df_bal[target].value_counts().to_dict())

# Helper 6: simple reporter to summarize key issues (optional)
def report_summary(df, target='Diabetes_binary'):
    """
    Return a small dict summary: counts, duplicates, target mean, numeric outlier flags (IQR counts),
    and top correlations to target.
    """
    out = {}
    out['rows'] = len(df)
    out['cols'] = df.shape[1]
    out['duplicates'] = df.duplicated().sum()
    if target in df.columns:
        out['target_mean'] = float(df[target].mean())
        out['target_counts'] = df[target].value_counts().to_dict()
    # numeric IQR outlier counts for selected columns that were flagged in profile
    numeric = df.select_dtypes(include=[np.number]).columns.tolist()
    iqr_outliers = {}
    for col in ['BMI', 'MentHlth', 'PhysHlth']:
        if col in df.columns:
            s = df[col].dropna()
            q1, q3 = s.quantile(0.25), s.quantile(0.75)
            iqr = q3 - q1
            lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
            iqr_outliers[col] = int(((s < lower) | (s > upper)).sum())
    out['iqr_outliers_sample_cols'] = iqr_outliers
    # top absolute correlations with target
    if target in numeric:
        corrs = df[numeric].corr()[target].abs().sort_values(ascending=False)
        out['top_corrs_with_target'] = corrs.head(10).to_dict()
    return out

# Wrapper function that calls the helpers based on user options
def preprocess(
    df,
    target='Diabetes_binary',
    remove_duplicates_flag=True,
    convert_binaries_flag=True,
    cap_outliers_flag=True,
    outlier_cols=None,
    drop_correlated_flag=True,
    corr_threshold=0.45,
    balance_flag=False,
    balance_method='undersample',
    balance_random_state=42,
    inplace=False
):
    """
    Run a sequence of data-prep steps based on boolean flags.
    Returns: df_processed, report where report contains information about actions taken.
    """
    report = {}
    if not inplace:
        df = df.copy()
    # 0) initial summary
    report['initial_rows'] = len(df)
    report['initial_cols'] = df.shape[1]
    # 1) remove duplicates
    if remove_duplicates_flag:
        df, removed = remove_duplicates(df, inplace=True)
        report['duplicates_removed'] = int(removed)
    else:
        report['duplicates_removed'] = 0
    # 2) convert binary floats
    if convert_binaries_flag:
        df, converted = convert_binary_floats(df, inplace=True, as_category=False)
        report['binary_cols_converted'] = converted
    else:
        report['binary_cols_converted'] = []
    # 3) cap outliers on specified continuous columns (default to BMI, MentHlth, PhysHlth)
    if cap_outliers_flag:
        if outlier_cols is None:
            # choose sensible defaults based on profile
            outlier_cols = [c for c in ['BMI', 'MentHlth', 'PhysHlth'] if c in df.columns]
        df, caps = cap_outliers_iqr(df, cols=outlier_cols, factor=1.5, inplace=True)
        report['outlier_caps'] = caps
    else:
        report['outlier_caps'] = {}
    # 4) drop correlated features
    if drop_correlated_flag:
        df, dropped = drop_correlated(df, target=target, threshold=corr_threshold, inplace=True, exclude=None)
        report['dropped_correlated'] = dropped
    else:
        report['dropped_correlated'] = []
    # 5) optional simple balancing
    if balance_flag:
        df, counts = balance_target_simple(df, target=target, method=balance_method, random_state=balance_random_state, inplace=True)
        report['balanced_counts'] = counts
        report['balance_method'] = balance_method
    else:
        report['balanced_counts'] = None
    # final summary
    report['final_rows'] = len(df)
    report['final_cols'] = df.shape[1]
    # include small summary
    report['summary'] = report_summary(df, target=target)

    return df, report


# Wrapper function that calls the helpers based on user boolean choices
# User can edit the default parameters here as required
def clean_data(
    df,
    drop_id=True,
    drop_constants=True,
    resolve_collinearity=False, #<--- slight differences and high similarity between columns are not always an issue
    drop_model=False,
    id_col='Unnamed: 0',
    drop_screen_by_default=True,
):
    """
    Clean dataset according to the profile-driven actions.
    Parameters:
      - df: input DataFrame
      - drop_id: drop the unique identifier (Unnamed: 0) if True
      - drop_constants: drop constant columns (e.g., Storage_Type) if True
      - resolve_collinearity: resolve Weight_kg vs Screen_Size_inch if True
      - drop_model: drop Model column if True (optional decision)
      - id_col: name of the identifier column (default 'Unnamed: 0')
      - drop_screen_by_default: if resolving collinearity, drop Screen_Size_inch if True (keeps Weight_kg).
    Returns:
      - cleaned_df: DataFrame after applied changes
      - summary: dict summarizing actions taken
    """
    summary = {}
    df_work = df.copy()
    # 1. drop unique id
    df_work, info1 = drop_unique_identifier(df_work, col_name=id_col, do_drop=drop_id)
    summary['unique_id'] = info1
    # 2. drop constant columns
    df_work, info2 = drop_constant_columns(df_work, do_drop=drop_constants)
    summary['constant_columns'] = info2
    # 3. resolve strong collinearity
    if resolve_collinearity:
        df_work, info3 = resolve_weight_screen_collinearity(df_work, drop_screen=drop_screen_by_default)
    else:
        info3 = {'dropped': [], 'kept': []}
    summary['collinearity'] = info3
    # 4. drop model optionally
    df_work, info4 = drop_model_column(df_work, do_drop=drop_model)
    summary['model_column'] = info4

    return df_work, summary

# Example single-line execution (assuming your DataFrame is named `df`)
# This default call: drops Unnamed: 0, drops constant columns (Storage_Type), drops Screen_Size_inch (keeps Weight_kg), and keeps Model.
# To drop Model as well, set drop_model=True.
cleaned_df, cleaning_summary = clean_data(df)

In [19]:
# Helper functions for the 'clean_data' wrapper function

def drop_unique_identifier(df, col_name, do_drop=True):
    """
    Drops a specified unique identifier column from the DataFrame if it exists.
    Returns the modified DataFrame and a dictionary indicating dropped columns.
    """
    dropped_cols = []
    if do_drop and col_name in df.columns:
        df = df.drop(columns=[col_name])
        dropped_cols.append(col_name)
    return df, {'dropped': dropped_cols}

def drop_constant_columns(df, do_drop=True):
    """
    Drops columns that have only one unique value (constant columns) if specified.
    Returns the modified DataFrame and a dictionary indicating dropped columns.
    """
    constant_cols = []
    if do_drop:
        for col in df.columns:
            if df[col].nunique(dropna=False) <= 1:
                constant_cols.append(col)
        df = df.drop(columns=constant_cols, errors='ignore') # Use errors='ignore' if some columns might have been dropped already
    return df, {'dropped': constant_cols}

def resolve_weight_screen_collinearity(df, drop_screen=True):
    """
    Resolves hypothetical collinearity between 'Weight_kg' and 'Screen_Size_inch'
    by dropping one. This function is specific to a laptop dataset context.
    Returns the modified DataFrame and a dictionary indicating dropped/kept columns.
    """
    dropped_cols = []
    kept_cols = []
    if 'Weight_kg' in df.columns and 'Screen_Size_inch' in df.columns:
        if drop_screen:
            df = df.drop(columns=['Screen_Size_inch'])
            dropped_cols.append('Screen_Size_inch')
            kept_cols.append('Weight_kg')
        else: # Implies keeping Screen_Size_inch and dropping Weight_kg
            df = df.drop(columns=['Weight_kg'])
            dropped_cols.append('Weight_kg')
            kept_cols.append('Screen_Size_inch')
    elif 'Weight_kg' in df.columns:
        kept_cols.append('Weight_kg')
    elif 'Screen_Size_inch' in df.columns:
        kept_cols.append('Screen_Size_inch')
    return df, {'dropped': dropped_cols, 'kept': kept_cols}

def drop_model_column(df, do_drop=True):
    """
    Drops the 'Model' column if it exists and specified. This function is specific
    to a hypothetical laptop dataset context.
    Returns the modified DataFrame and a dictionary indicating dropped columns.
    """
    dropped_cols = []
    if do_drop and 'Model' in df.columns:
        df = df.drop(columns=['Model'])
        dropped_cols.append('Model')
    return df, {'dropped': dropped_cols}


In [ ]:
df_inline_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Diabetes_binary       254 non-null    float64
 1   HighBP                254 non-null    float64
 2   HighChol              254 non-null    float64
 3   CholCheck             254 non-null    float64
 4   BMI                   254 non-null    float64
 5   Smoker                254 non-null    float64
 6   Stroke                254 non-null    float64
 7   HeartDiseaseorAttack  254 non-null    float64
 8   PhysActivity          254 non-null    float64
 9   Fruits                254 non-null    float64
 10  Veggies               254 non-null    float64
 11  HvyAlcoholConsump     254 non-null    float64
 12  AnyHealthcare         254 non-null    float64
 13  NoDocbcCost           254 non-null    float64
 14  GenHlth               254 non-null    float64
 15  MentHlth              2

In [ ]:
# Example: Replace this with the raw URL of your GitHub file
github_raw_url = 'https://raw.githubusercontent.com/hazelchiang2102/ADALL_github/refs/heads/main/diabetes_binary_health_indicators_BRFSS2015.csv'
try:
    df = pd.read_csv(github_raw_url)
    print("Successfully loaded data from GitHub!")
    display(df.head())
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please ensure the URL is correct and the file format is compatible with `pd.read_csv`.")

Successfully loaded data from GitHub!


Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [ ]:
#read in the dataset (select 2015)
year = '2015'
brfss_2015_dataset = pd.read_csv('/content/sample_data/diabetes_binary_health_indicators_BRFSS2015 (1).csv')

In [ ]:
#How many rows and columns
brfss_2015_dataset.shape

(253680, 22)

In [ ]:
#check that the data loaded in is in the correct format
pd.set_option('display.max_columns', 500)
brfss_2015_dataset.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  \
0                   0.0           0.0     0.0      1.0                0.0   
1                   0.0           1.0     0.0      0.0                0.0   
2                   0.0           0.0     1.0      0.0                0.0   
3                   0.0           1.0     1.0      1.0                0.0   
4                   0.0           1.0     1.0      1.0                0.0   

   AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
0            1.0          0.0      5.0      18.0      15.0       1.0  0.0   
1            0.0          1.0      3.0       0.0       0.0       0.0  0.0   
2            1.0          1.0      5.0      30.0      30.0       1.0  0.0   
3            1.0          0.0      2.0       0.0       0.0       0.0  0.0   
4            1.0          0.0      2.0       3.0       0.0       0.0  0.0   

    Age  Education  Income  
0   9.0        4.0     3.0  
1   7.0        6.0     1.0  
2   9.0        4.0     8.0  
3  11.0        3.0     6.0  
4  11.0        5.0     4.0

In [ ]:
# select specific columns
brfss_df_selected = brfss_2015_dataset[['Diabetes_binary',
                                         'HighBP',
                                         'HighChol', 'CholCheck',
                                         'BMI',
                                         'Smoker',
                                         'Stroke', 'HeartDiseaseorAttack',
                                         'PhysActivity',
                                         'Fruits', 'Veggies',
                                         'HvyAlcoholConsump',
                                         'AnyHealthcare', 'NoDocbcCost',
                                         'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk',
                                         'Sex', 'Age', 'Education', 'Income' ]]

In [ ]:
brfss_df_selected.shape

(253680, 22)

In [ ]:
brfss_df_selected.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  \
0                   0.0           0.0     0.0      1.0                0.0   
1                   0.0           1.0     0.0      0.0                0.0   
2                   0.0           0.0     1.0      0.0                0.0   
3                   0.0           1.0     1.0      1.0                0.0   
4                   0.0           1.0     1.0      1.0                0.0   

   AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
0            1.0          0.0      5.0      18.0      15.0       1.0  0.0   
1            0.0          1.0      3.0       0.0       0.0       0.0  0.0   
2            1.0          1.0      5.0      30.0      30.0       1.0  0.0   
3            1.0          0.0      2.0       0.0       0.0       0.0  0.0   
4            1.0          0.0      2.0       3.0       0.0       0.0  0.0   

    Age  Education  Income  
0   9.0        4.0     3.0  
1   7.0        6.0     1.0  
2   9.0        4.0     8.0  
3  11.0        3.0     6.0  
4  11.0        5.0     4.0

In [ ]:
#Drop Missing Values - knocks 100,000 rows out right away
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(253680, 22)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [ ]:
from google.colab import userdata
from openai import OpenAI

# Load key from Google Colab Secrets
api_key = userdata.get('OPENAI_API_KEY')

client = OpenAI(
    api_key=api_key
)

In [ ]:
# Diabetes_binary (originally intended as DIABETE3)
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Note: The 'Diabetes_binary' column currently contains 0.0 (no diabetes) and 1.0 (diabetes).
# To align with the desired 0, 1, 2 scale, we will map 1.0 to 2.0. The pre-diabetes category (1) cannot be derived from this binary column.
# The original comments and replacement mapping seem to refer to a different source column with more categories.
brfss_df_selected['Diabetes_binary'] = brfss_df_selected['Diabetes_binary'].replace({1:2})
# Remove all 7 (dont knows) and 9 (refused) - these values are not present in Diabetes_binary based on initial inspection.
# brfss_df_selected = brfss_df_selected[brfss_df_selected.Diabetes_binary != 7]
# brfss_df_selected = brfss_df_selected[brfss_df_selected.Diabetes_binary != 9]
brfss_df_selected['Diabetes_binary'].unique()

array([0., 2.])

In [ ]:
#generate a preview of ten rows as text first, so that we can use it for sending to LLM API later.
data_preview = df.head(10).to_string()
print(data_preview)

   Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0                   0.0           0.0     0.0      1.0                0.0            1.0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0     3.0
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0                   0.0           1.0     0.0      0.0                0.0            0.0          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0     1.0
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0                   0.0           0.0     1.0      0.0                0.0            1.0          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0     8.0
3              0.0     1.0       0.0        

In [ ]:
#sending to LLM API
response = client.responses.create(
    model="gpt-5-mini",
    instructions="""
You are an expert data scientist with extensive knowledge of tree-based models.
Use ONLY the information inside the dataset profile text.
Do NOT invent correlations, columns, or values.
If something is not in the dataset profile, state 'Not shown in profile'.
Always justify recommendations using reasoning trace based ONLY on the dataset profile.
""",
    input=f"""Dataset info: {data_preview}\n
    Context:
    The business problem is that a refurbished laptop store wants to understand and predict the retail price of its laptops based on their specifications.\n
    Questions
    1. Based on the context and dataset info, how should i approach modelling objective? focus on problem framing aspects.
    2. What would be the most meaningful target?
    3. What would be most important metric for scoring?
    4. What are the top 3 most potentially important features?
    """)
print(response.output_text)

Short answer up-front
- There is a fundamental mismatch: the file you pasted contains health / survey variables (Diabetes_binary, HighBP, BMI, Age, …). It does NOT contain laptop specifications or any retail price. If your goal really is “predict refurbished laptop retail price”, the necessary target and laptop-spec features are Not shown in profile and you cannot build that model from this dataset.
- If instead you want to model something useful with the data you actually have, the natural problem in the profile is to predict Diabetes_binary (a binary label). Below I give the recommended framing, metric and likely important features for that task using only the columns shown.

1) Modelling-objective & problem framing (based only on the profile)
- If your real objective = laptop price prediction: required target (price) and laptop features (make, model, CPU, RAM, storage, age, condition, warranty, etc.) are Not shown in profile. Collect a dataset with those fields first.
- For the data

In [ ]:
df.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np
from io import StringIO

# ---------------------------
# Generate a full dataset profile
# ---------------------------

buffer = StringIO()

# dtypes
buffer.write("=== DTYPES ===\n")
buffer.write(df.dtypes.to_string())
buffer.write("\n\n")

# numeric describe
buffer.write("=== NUMERIC DESCRIBE ===\n")
buffer.write(df.describe().to_string())
buffer.write("\n\n")

# categorical describe
buffer.write("=== CATEGORICAL DESCRIBE ===\n")
try:
    buffer.write(df.describe(include='object').to_string())
except:
    buffer.write("No categorical columns")
buffer.write("\n\n")

# null summary
buffer.write("=== NULL SUMMARY ===\n")
null_summary = (
    df.isna().sum().to_frame("null_count")
    .assign(null_pct=lambda x: x["null_count"]/len(df))
)
buffer.write(null_summary.to_string())
buffer.write("\n\n")

# unique cardinality
buffer.write("=== UNIQUE VALUES PER COLUMN ===\n")
buffer.write(df.nunique().to_frame("unique_count").to_string())
buffer.write("\n\n")

# correlation matrix
buffer.write("=== CORRELATIONS (NUMERIC ONLY) ===\n")
buffer.write(df.corr(numeric_only=True).round(3).to_string())
buffer.write("\n\n")

# value counts for categoricals
buffer.write("=== VALUE COUNTS (TOP 20 PER CATEGORICAL COLUMN) ===\n")
cat_cols = df.select_dtypes(include='object').columns
if len(cat_cols) > 0:
    for col in cat_cols:
        buffer.write(f"\nColumn: {col}\n")
        vc = df[col].value_counts().head(20)
        buffer.write(vc.to_string())
        buffer.write("\n")
else:
    buffer.write("No categorical columns\n")
buffer.write("\n")

# --------- FIXED OUTLIER COMPUTATION (NO BOOLEANS) ---------
buffer.write("=== OUTLIER SUMMARY (IQR METHOD) ===\n")
num_cols = df.select_dtypes(include=['number']).columns  # exclude booleans
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1
outliers = ((df[num_cols] < (Q1 - 1.5*IQR)) | (df[num_cols] > (Q3 + 1.5*IQR))).sum()
buffer.write(outliers.to_string())
buffer.write("\n\n")

# leakage scan: columns with all unique values
buffer.write("=== POSSIBLE LEAKAGE COLUMNS (UNIQUE FOR EACH ROW) ===\n")
leak_cols = df.columns[df.nunique() == len(df)]
buffer.write(str(list(leak_cols)))
buffer.write("\n\n")

# shape, duplicates, constant cols
buffer.write("=== SHAPE / DUPLICATES / CONSTANT COLUMNS ===\n")
dup_count = df.duplicated().sum()
constant_cols = df.columns[df.nunique() == 1].tolist()
buffer.write(f"Rows: {len(df)}, Columns: {df.shape[1]}\n")
buffer.write(f"Duplicate rows: {dup_count}\n")
buffer.write(f"Constant columns: {constant_cols}\n\n")

# Final text
payload_text = buffer.getvalue()

print(payload_text)


=== DTYPES ===
Diabetes_binary         float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
HeartDiseaseorAttack    float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64

=== NUMERIC DESCRIBE ===
       Diabetes_binary         HighBP       HighChol      CholCheck            BMI         Smoker         Stroke  HeartDiseaseorAttack   PhysActivity         Fruits        Veggies  HvyAlcoholConsump  AnyHealthcare    NoDocbcCost        GenHlth       MentH

In [ ]:
#1 HighBP
# Confirming unique values. Original values 1.0 and 0.0 are already correct (1 for high blood pressure, 0 for no).
brfss_df_selected.HighBP.unique()

array([1., 0.])

In [ ]:
#2 TOLDHI2
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI2'] = brfss_df_selected['TOLDHI2'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI2 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI2 != 9]
brfss_df_selected.TOLDHI2.unique()

array([1., 0.])

In [ ]:
#3 _CHOLCHK
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9
brfss_df_selected['_CHOLCHK'] = brfss_df_selected['_CHOLCHK'].replace({3:0,2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCHK != 9]
brfss_df_selected._CHOLCHK.unique()

array([1., 0.])

In [ ]:
#4 _BMI5 (no changes, just note that these are BMI * 100. So for example a BMI of 4018 is really 40.18)
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([40., 25., 28., 24., 27., 30., 26., 23., 34., 33., 21., 22., 31.,
       38., 20., 19., 32., 46., 41., 37., 36., 29., 35., 18., 54., 45.,
       39., 47., 43., 55., 49., 42., 17., 16., 48., 44., 50., 59., 15.,
       52., 53., 57., 51., 14., 58., 63., 61., 56., 60., 74., 62., 64.,
       13., 66., 73., 65., 68., 85., 71., 84., 67., 70., 82., 79., 92.,
       72., 88., 96., 81., 12., 77., 95., 75., 91., 69., 76., 87., 89.,
       83., 98., 86.])

In [ ]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([1., 0.])

In [ ]:
#7 _MICHD
#Change 2 to 0 because this means did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [ ]:
#8 _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [ ]:
#9 _FRTLT1
# Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day
# remove all dont knows and missing 9
brfss_df_selected['_FRTLT1'] = brfss_df_selected['_FRTLT1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1 != 9]
brfss_df_selected._FRTLT1.unique()

array([0., 1.])

In [ ]:
#10 _VEGLT1
# Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day
# remove all dont knows and missing 9
brfss_df_selected['_VEGLT1'] = brfss_df_selected['_VEGLT1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1 != 9]
brfss_df_selected._VEGLT1.unique()

array([1., 0.])

In [ ]:
#11 _RFDRHV5
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
brfss_df_selected['_RFDRHV5'] = brfss_df_selected['_RFDRHV5'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV5 != 9]
brfss_df_selected._RFDRHV5.unique()

array([0., 1.])

In [ ]:
#12 HLTHPLN1
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
brfss_df_selected['HLTHPLN1'] = brfss_df_selected['HLTHPLN1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 9]
brfss_df_selected.HLTHPLN1.unique()

array([1., 0.])

In [ ]:
#13 MEDCOST
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
brfss_df_selected['MEDCOST'] = brfss_df_selected['MEDCOST'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 9]
brfss_df_selected.MEDCOST.unique()

array([0., 1.])

In [ ]:
#14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([5., 3., 2., 4., 1.])

In [ ]:
#15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([18.,  0., 30.,  3.,  5., 15., 10.,  6., 20.,  2., 25.,  1., 29.,
        4.,  7.,  8., 21., 14., 26.,  9., 16., 28., 11., 12., 23., 24.,
       17., 13., 27., 19., 22.])

In [ ]:
#16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([15.,  0., 30.,  2., 14., 28.,  7., 20.,  3., 10.,  1.,  5., 17.,
        4., 19.,  6., 21., 12.,  8., 25., 27., 22., 29., 24.,  9., 16.,
       18., 23., 13., 26., 11.])

In [ ]:
#17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([1., 0.])

In [ ]:
#18 SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
brfss_df_selected['SEX'] = brfss_df_selected['SEX'].replace({2:0})
brfss_df_selected.SEX.unique()

array([0., 1.])

In [ ]:
#19 _AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([ 9.,  7., 11., 10., 13.,  8.,  4.,  6.,  2., 12.,  5.,  1.,  3.])

In [ ]:
#20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 6., 3., 5., 2., 1.])

In [ ]:
#21 INCOME2
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 99]
brfss_df_selected.INCOME2.unique()

array([3., 1., 8., 6., 4., 7., 2., 5.])

In [ ]:
#Check the shape of the dataset now: We have 253,680 cleaned rows and 22 columns (1 of which is our dependent variable)
brfss_df_selected.shape

(98210, 22)

In [ ]:
#Let's see what the data looks like after Modifying Values
brfss_df_selected.head()

DIABETE3  _RFHYPE5  TOLDHI2  _CHOLCHK  _BMI5  SMOKE100  CVDSTRK3  _MICHD  \
0       0.0       1.0      1.0       1.0   40.0       1.0       2.0     0.0   
1       0.0       0.0      0.0       0.0   25.0       1.0       2.0     0.0   
3       0.0       1.0      1.0       1.0   28.0       0.0       2.0     0.0   
5       0.0       1.0      0.0       1.0   27.0       0.0       2.0     0.0   
6       0.0       1.0      1.0       1.0   24.0       0.0       2.0     0.0   

   _TOTINDA  _FRTLT1  _VEGLT1  _RFDRHV5  HLTHPLN1  MEDCOST  GENHLTH  MENTHLTH  \
0       0.0      0.0      1.0       0.0       1.0      0.0      5.0      18.0   
1       1.0      0.0      0.0       0.0       0.0      1.0      3.0       0.0   
3       0.0      1.0      0.0       0.0       1.0      1.0      5.0      30.0   
5       1.0      1.0      1.0       0.0       1.0      0.0      2.0       0.0   
6       1.0      1.0      1.0       0.0       1.0      0.0      2.0       3.0   

   PHYSHLTH  DIFFWALK  SEX  _AGEG5YR  EDUCA  INCOME2  
0      15.0       1.0  0.0       9.0    4.0      3.0  
1       0.0       0.0  0.0       7.0    6.0      1.0  
3      30.0       1.0  0.0       9.0    4.0      8.0  
5       0.0       0.0  0.0      11.0    3.0      6.0  
6       0.0       0.0  0.0      11.0    5.0      4.0

In [ ]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE3']).size()

DIABETE3
0.0    82571
1.0     1861
2.0    13778
dtype: int64

In [ ]:
#Rename the columns to make them more readable#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE3':'Diabetes_012',
                                         '_RFHYPE5':'HighBP',
                                         'TOLDHI2':'HighChol', '_CHOLCHK':'CholCheck',
                                         '_BMI5':'BMI',
                                         'SMOKE100':'Smoker',
                                         'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack',
                                         '_TOTINDA':'PhysActivity',
                                         '_FRTLT1':'Fruits', '_VEGLT1':"Veggies",
                                         '_RFDRHV5':'HvyAlcoholConsump',
                                         'HLTHPLN1':'AnyHealthcare', 'MEDCOST':'NoDocbcCost',
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk',
                                         'SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME2':'Income' })

In [ ]:
brfss.head()

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0           0.0     1.0       1.0        1.0  40.0     1.0     2.0   
1           0.0     0.0       0.0        0.0  25.0     1.0     2.0   
3           0.0     1.0       1.0        1.0  28.0     0.0     2.0   
5           0.0     1.0       0.0        1.0  27.0     0.0     2.0   
6           0.0     1.0       1.0        1.0  24.0     0.0     2.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  \
0                   0.0           0.0     0.0      1.0                0.0   
1                   0.0           1.0     0.0      0.0                0.0   
3                   0.0           0.0     1.0      0.0                0.0   
5                   0.0           1.0     1.0      1.0                0.0   
6                   0.0           1.0     1.0      1.0                0.0   

   AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
0            1.0          0.0      5.0      18.0      15.0       1.0  0.0   
1            0.0          1.0      3.0       0.0       0.0       0.0  0.0   
3            1.0          1.0      5.0      30.0      30.0       1.0  0.0   
5            1.0          0.0      2.0       0.0       0.0       0.0  0.0   
6            1.0          0.0      2.0       3.0       0.0       0.0  0.0   

    Age  Education  Income  
0   9.0        4.0     3.0  
1   7.0        6.0     1.0  
3   9.0        4.0     8.0  
5  11.0        3.0     6.0  
6  11.0        5.0     4.0

In [ ]:
brfss.shape

(98210, 22)

In [ ]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes_012']).size()

Diabetes_012
0.0    82571
1.0     1861
2.0    13778
dtype: int64

In [ ]:
#************************************************************************************************
brfss.to_csv('diabetes_012_health_indicators_BRFSS2015.csv', sep=",", index=False)
#************************************************************************************************